# Generated by Django 2.0 on 2019-09-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20190919_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
